version: '3.8'

services:
    bot:
        container_name: grammy1
        build:
            context: .
            dockerfile: Dockerfile
        stop_signal: SIGINT
        restart: on-failure
        env_file: .env