[fonts]
packages = ["noto-fonts"]

[build]
packages = ["fontconfig", "freetype", "fontconfig-config"]

[phases.setup]
commands = [
  "mkdir -p /etc/fonts/conf.d",
  "echo '<?xml version=\"1.0\"?>\n<!DOCTYPE fontconfig SYSTEM \"fonts.dtd\">\n<fontconfig>\n  <dir>/nix/store/*-noto-fonts-*/share/fonts</dir>\n</fontconfig>' > /etc/fonts/fonts.conf"
]

[env]
FONTCONFIG_PATH = "/etc/fonts"