# nixpacks.toml

[phases.setup]
nixPkgs = ["noto-fonts", "fontconfig", "freetype"]
cmds = [
  "mkdir -p /etc/fonts/conf.d",
  "sh setup-fontconfig.sh"
]

[phases.build]
cmds = ["npm ci --omit=dev"]

[start]
cmd = "npm start"

[env]
FONTCONFIG_PATH = "/etc/fonts"